config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # users routes (Devise)
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # results routes
  get "results", to: "restaurants#index"

  # temp list routes
  post "temp_list", to: "lists#show"

  # reviews route
  resources :restaurants do
    resources :reviews, only: [:show, :create, :new]
    resources :calendars, only: [:create]
  end

  # lists route
  resources :users do
    resources :lists
  end

  # tags route
  resources :restaurants do
    resources :tags
  end

  # explores route
  resources :restaurants do
    resources :explores
  end

  # calendars route
  resources :users do
    resources :calendars, only: [:index]
  end

end

app/views/shared/_copytoclipboard.html.erb
<!-- Copy-to-clipboard card -->
<div class="copy-to-clipboard ml-2 shadow bg-white rounded" data-controller="clipboard" data-clipboard-feedback-text-value="Copied!">
  <h2 class="teal">Wanna share this list?</h2>
  <input class="form-control" data-clipboard-target="input" type="text" value="<%= request.original_url %>" readonly>
  <button id="copy-button" class="btn border btn-flat mt-3" data-action="click->clipboard#copy">Copy to Clipboard</button>
</div>

app/views/shared/_dropdown.html.erb
<li class="nav-item dropdown">
    <%= image_tag "avatar.jpg", class:"avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle:"dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to "My schedule", user_calendars_path(current_user), class:"dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
    </div>
</li>

app/views/shared/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>
<p><%= restaurant.genre %></p>
<p>Rating: <%= restaurant.avg_rating %> / 5.0</p>

app/views/shared/_listmap.html.erb
<!-- Map wrapper -->
<div  class="listmapcontent d-flex justify-content-start align-items-center ml-1">
  <div class="shadow bg-white rounded" id="listmap" style="height: 300px; width: 640px;" data-markers="<%= markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <%= render "shared/copytoclipboard" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt:"My foodie list logo", class:"d-inline-block", top: "32px", left:"20px", width:"200px" %>
    <% end %>

    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <%- if current_user %>
            <li class="nav-item">
              <%= link_to "New list", results_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "My lists", user_lists_path(current_user), class:
                    "nav-link" %>
            </li>
            <%= render "shared/dropdown" %>
        <% else %>
            <li class="nav-item">
                <!-- Button trigger modal -->
                <button
                    type="button"
                    class="nav-link"
                    data-toggle="modal"
                    data-target="#exampleModalB">
                    Log in
                </button>
            </li>
            <li class="nav-item">
                <!-- Button trigger modal -->
                <button
                    type="button"
                    class="nav-link"
                    data-toggle="modal"
                    data-target="#exampleModalA">
                    Sign up
                </button>
            </li>
            <% end %>
        </ul>
    </div>
</div>
<%= render "devise/registrations/modal" %>
<%= render "devise/sessions/modal" %>

app/views/shared/_navsearchbar.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt:"My foodie list logo", class:"d-inline-block", left:"20px", width:"200px" %>
    <% end %>

    <%= render 'shared/search' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <%- if current_user %>
            <li class="nav-item">
              <%= link_to "New list", results_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "My lists", user_lists_path(current_user), class:
                    "nav-link" %>
            </li>
            <%= render "shared/dropdown" %>
        <% else %>
            <li class="nav-item">
                <!-- Button trigger modal -->
                <button
                    type="button"
                    class="nav-link"
                    data-toggle="modal"
                    data-target="#exampleModalB">
                    Log in
                </button>
            </li>
            <li class="nav-item">
                <!-- Button trigger modal -->
                <button
                    type="button"
                    class="nav-link"
                    data-toggle="modal"
                    data-target="#exampleModalA">
                    Sign up
                </button>
            </li>
            <% end %>
        </ul>
    </div>
</div>
<%= render "devise/registrations/modal" %>
<%= render "devise/sessions/modal" %>

app/views/shared/_quickpicks.html.erb
  <!-- Home page & list page quick picks -->
  <section class="features-icons text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="card-shop">
          <a href="/results?query=spanish">
            <img src="https://images.unsplash.com/photo-1571167366136-b57e07761625?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80" class="card-img-top" alt="spanish food list" />
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex mb-2">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Spanish</h3>
              <p class="lead mb-0">Enjoy the best tapas and iberico ham!</p>
            </div>
          </a>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card-shop">
          <a href="/results?query=cantonese">
          <img src="https://images.unsplash.com/photo-1495899686424-be6ded54191a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" class="card-img-top" alt="indonesian food list"/>
              <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
                <div class="features-icons-icon d-flex mb-2">
                  <i class="icon-screen-desktop m-auto text-primary"></i>
                </div>
                <h3>Cantonese</h3>
                <p class="lead mb-0">The search for the nicest dim sum continues!</p>
              </div>
            </div>
          </a>
          </div>
        <div class="col-lg-4">
          <div class="card-shop">
          <a href="/results?query=local">
          <img src="https://images.unsplash.com/photo-1605464370799-719bc1bfba78?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8ZmF2b3VyaXRlJTIwaGVhcnR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" class="card-img-top" alt="die die must eat food list" />
            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
              <div class="features-icons-icon d-flex mb-2">
                <i class="icon-screen-desktop m-auto text-primary"></i>
              </div>
              <h3>Go local!</h3>
              <p class="lead mb-0">Discover local restaurants selection!</p>
            </div>
          </div>
        </div>
        </div>
    </div>
  </section>

app/views/shared/_restomap.html.erb
<!-- Map wrapper -->
<div class="col-6 d-flex justify-content-center restomapcontent" id="restomap" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/shared/_search.html.erb
<!-- Banner & Search Bar -->
<div class="container search-bar-container">
  <div class="wrap">
    <%= simple_form_for :search, url: '/results', method: :get do |f| %>
      <div class="d-flex search-form-control form-group">
        <input class="form-control input-lg" type="text" name="query" id="query" placeholder="Start your food search here" />
        <button type="submit" class="searchButton">
          <i class="fas fa-search fa-2x"></i>
        </button>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
        <p class="alert-main"><%= alert %></p>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="resultsidebar">

  <div class="form-group">
    <input data-list-target="namelistnew" type="text" class="form-control" id="namelistnew" placeholder="Name Me!">
  </div>
  <table>
    <div data-list-target="temp" id="temp-list">
    </div>
  </table>
  <!-- user logged in -->
    <div class="btn btn-primary deleteL">
      <%= link_to "Clear list" %>
    </div>

  <% if current_user %>
      <%= link_to "Create new list", new_user_list_path(current_user), data: {action: "click->list#createNewList"}, class:"btn btn-flat-reverse my-2"%>
  <% else %>
    <div>
      <button class="btn btn-flat-reverse dropdown-toggle " type="button" id="drop-down" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Register to continue!
      </button>
      <div class="dropdown-menu" aria-labelledby="drop-down">
            <button
                      type="button"
                      class="dropdown-item"
                      data-toggle="modal"
                      data-target="#exampleModalB">
                      Log in
            </button>
            <button
                      type="button"
                      class="dropdown-item"
                      data-toggle="modal"
                      data-target="#exampleModalA">
                      Sign up
            </button>
      </div>
    </div>
  <% end %>
</div>