config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # users routes (Devise)
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # results routes
  get "results", to: "restaurants#index"

  # temp list routes
  post "temp_list", to: "lists#show"

  # reviews route
  resources :restaurants do
    resources :reviews, only: [:show, :create, :new]
    resources :calendars, only: [:create]
  end

  # lists route
  resources :users do
    resources :lists
  end

  # tags route
  resources :restaurants do
    resources :tags
  end

  # explores route
  resources :restaurants do
    resources :explores
  end

  # calendars route
  resources :users do
    resources :calendars, only: [:index]
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Name of restaurant, must have name, name must be unique and minimum 3 characters
  validates :name, presence: true, length: { minimum: 3 }

  # Must have address, at least 6 characters
  validates :address, presence: true, length: { minimum: 6 }

  # Must have genre
  validates :genre, presence: true

  # Must have postal code, must be numbers, exact length is 6
  validates :postal_code, presence: true
  validates :postal_code, length: { is: 6 }

  # Associations
  has_one_attached :photo
  has_many :restaurant_lists, dependent: :destroy
  has_many :lists, through: :restaurant_lists
  has_many :reviews, dependent: :destroy
  has_many :calendars, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :explores, dependent: :destroy

  def avg_rating
    rev_arr = reviews
    total_rating = 0
    rev_arr.each do |rate|
      total_rating += rate.rating
    end
    processed_rating = total_rating / reviews.count
    return processed_rating.round(1)
  end

  def tag_names
    return tags.empty? ? [] : tags.map(&:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @query_value = params[:query]
    @sort_by = params[:sort_by]
    @filter_by = params[:filter_by]
    @sort_order = params[:sort_order]
    alert = "#{@query_value} is not found. Please try another search."

    # Keyword search result
    if params[:query].present? && /\d{6}/ === @query_value
      @restaurants = Restaurant.where(postal_code: @query_value)
    elsif params[:query].present?
      @sql_query = "restaurants.name @@ :query OR restaurants.address @@ :query OR restaurants.genre @@ :query"
      @restaurants = Restaurant.all.where(@sql_query, query: "%#{@query_value}%").distinct
    else
      @restaurants = Restaurant.all
    end
    if @restaurants.nil? || @restaurants.empty?
      flash[:alert] = alert
    end

    # Filtering
    filter_restaurants if @filter_by.present?

    # Sorting
    sort_restaurants if @sort_by.present?
  end

  def show
    @query = params[:query]
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    @calendar = Calendar.new
    @tag = Tag.new
    @explore = Explore.new
    @markers = [JSON.parse(@restaurant.coordinates)]
    @drop_down = ["Rate your experience", 1, 2, 3, 4, 5 ]

  end

  def new
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    @tag = Tag.new
  end

  def create
    @restaurant = Restaurant.find(params[:id])
    render :new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :genre, :postal_code, :photo)
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def filter_restaurants
    filter_query = "tags.name @@ :sub_query"
    @restaurants = @restaurants.joins(:tags).where(filter_query, sub_query: "%#{@filter_by}%").distinct
  end

  def sort_restaurants
    if (@sort_by == "name" || @sort_by == "genre") && @sort_order.present?
      @restaurants = @restaurants.order("#{@sort_by} #{@sort_order.upcase}")
    elsif !@sort_order.present?
      @restaurants = @restaurants.order("#{@sort_by} ASC")
    elsif @sort_order == "asc"
      @restaurants = @restaurants.to_a.sort_by { |restaurant| restaurant.avg_rating }
    else
      @restaurants = @restaurants.to_a.sort_by { |restaurant| restaurant.avg_rating }.reverse!
    end
  end
end

app/views/restaurants/_rating.html.erb
<% rev_arr = @restaurant.reviews %>
<% total_rate = 0 %>
<% avg_rating = rev_arr.each do |review| %>
<% review.rating += total_rate %>
<% end %>

app/views/restaurants/index.html.erb
<div data-controller="list">

  <%= render 'shared/navsearchbar' %>
  <div class="container-fluid">
    <% if !@query_value || @query_value == "" %>
      <h1>Displaying All Restaurants</h1>
      <p class="pl-2">Showing <%= @restaurants.count %> results</p>
    <% else %>
      <h1>Displaying Results for "<%= @query_value %>"</h1>
      <p class="pl-2">Showing <%= @restaurants.count %> results</p>
    <% end %>
  </div>
  <!-- Filtering and Sorting -->
  <div class="d-flex justify-content-start ml-3">
    <%= simple_form_for :results, url: results_path, method: :get, html: { class: "d-flex align-items-center filtering-sorting-form" } do |f| %>
      <input type="hidden" name="query" value="<%= @query_value %>">
      <select name="sort_by" class="btn-flat my-1">
        <option value="">Sort by</option>
        <option <%= params["sort_by"] == "name" ? "selected":"" %> value="name">Restaurant Name</option>
        <option <%= params["sort_by"] == "genre" ? "selected":"" %> value="genre">Cuisine Type</option>
        <option <%= params["sort_by"] == "avg_rating" ? "selected":"" %> value="avg_rating">Average Rating</option>
      </select>
      <select name="sort_order" class="btn-flat my-1">
        <option value="">Order</option>
        <option <%= params["sort_order"] == "asc" ? "selected":"" %> value="asc">Ascending</option>
        <option <%= params["sort_order"] == "desc" ? "selected":"" %> value="desc">Descending</option>
      </select>
      <input type="text" name="filter_by" placeholder="<%= (params["filter_by"] && !params["filter_by"].empty?) ? "#{params["filter_by"]}" : "Filter" %>" class="btn-flat my-1">
      <button class="btn btn-flat-reverse" type="submit">Show me!</button>
    <% end %>
  </div>

  <!-- Restaurants search results -->
  <div class="container">

    <div class="resto-grid position-absolute">
      <% @restaurants.each do |restaurant| %>
          <div class="card-resto">
          <!-- begin inner container -->
            <div class="p-3">
              <h2 class="text-left rest-name"><u><%= restaurant.name.first(60) %></u></h2>
            <!-- begins contains image and desc -->
              <div class="d-flex">
          <!-- Image -->
                <%= cl_image_tag(restaurant.photo.key, :transformation=>[
                  {height: 160, width: 240, crop: :fill},
                  {:radius=>12}]) %>

                <!-- Restaurant Info -->
                <div class="ml-4">
                  <div>
                    <p class="pl-2">Address: <strong><%= restaurant.address %></strong></p>
                    <p class="pl-2">Postal code: <strong><%= restaurant.postal_code %></strong></p>
                    <p class="pl-2">Cuisine type: <strong><%= restaurant.genre %></strong></p>
                    <p class="pl-2">Average rating: <strong><%= restaurant.avg_rating %>/5.0</strong></p>
                    <p class="pl-2">Tags:
                      <% if restaurant.tag_names.empty? %>
                        <strong><%= "None" %></strong>
                      <% else %>
                        <strong><%= restaurant.tag_names.sample(2).join(', ') %> ...</strong>
                      <% end %>
                    </p>
                  </div>
                </div>
              </div>
            <!-- end of image and desc div -->

            <!-- begins contains two links -->
              <div class="img-info p-2 rest-info">
                <div id="copy-button" class="btn border btn-flat">
                  <%= link_to restaurant_path(restaurant, query: @query_value) do %>
                    <i class="fas fa-info-circle"></i> See Details
                  <% end %>
                </div>
              <!-- "Plus Button" -->
                <div id="copy-button" class="btn border btn-flat">
                    <a href="" class="add-to-list"
                        data-restaurant-id=<%=restaurant.id%>
                        data-restaurant-name="<%=restaurant.name%>"><i class="fas fa-plus"></i> Add to List</a>
                </div>
              <!-- end of plus button -->
              </div>
            <!-- end of two links -->
            </div>
          </div>
        <% end %>
    </div>
    <!-- End of cards grid -->
  </div>
  <!-- End of card container -->
  <!-- Side bar to add to list -->
    <%= render 'shared/sidebar', restaurants: @restaurants %>
</div>

app/views/restaurants/show.html.erb
<%= stylesheet_pack_tag 'application' %>
<%= render 'shared/navsearchbar' %>

<h1><%= @restaurant.name %></h1>

<!-- Start Main-Body -->
<div class="container mt-4">
  <!-- Start Row 1 -->
  <div class="row">
    <!-- Start Photo-and-Details (Section 1) -->
    <div class="col-8 shadow bg-white d-flex justify-content-start resto-section-1 mb-4 mr-2">
      <!-- Start Photo-->
      <%= cl_image_tag @restaurant.photo.key, height: 300, width: 500 %>
      <!-- End Photo -->
      <!-- Start Details -->
      <div class="resto-details d-flex justify-content-center">
        <p>Address: <strong><%= @restaurant.address %></strong></p>
        <p>Postal code: <strong><%= @restaurant.postal_code %></strong></p>
        <p>Cuisine type: <strong><%= @restaurant.genre %></strong></p>
        <p>Average rating: <strong><%= @restaurant.avg_rating %>/5.0</strong></p>
      </div>
      <!-- End Details -->
    </div>
    <!-- End Photo-and-Details (Section 1) -->

    <!--  Start Switchboard (Section 2) -->
    <div id="card-bg" class="col-3 shadow bg-white d-flex justify-content-around resto-section-2 mb-4 mr-2">
      <!-- User logged in -->
      <% if current_user %>
        <!-- Start Mark-as-explored -->
        <% if current_user.explores.one? { |explored| explored.restaurant == @restaurant } %>
          <div>
            <button type="button" class="btn btn-flat-reverse" disabled>Explored!</button>
          </div>
        <% else %>
          <div class="d-flex justfy-content-end my-2">
            <%= simple_form_for [@restaurant, @explore], html: {class: 'form-inline explore-form'} do |f| %>
            <%= f.input :explored %>
            <% f.association :user %>
            <%= f.submit "Mark it!", class: "btn btn-flat" %>
            <% end %>
          </div>
        <% end %>
        <!-- End Mark-as-explored -->
        <!-- Start Calendar -->
        <%= simple_form_for [@restaurant, @calendar], html: {class: 'form-inline schedule-form'} do |f| %>
          <input type="hidden" name="restaurant" value="<%= @restaurant %>">
          <%= f.input :scheduled_date, html5: true, label: false %>
          <%= f.button :submit, value: "Schedule a visit", class: 'btn btn-flat' %>
        <% end %>
        <!-- End Calendar -->
      <% end %>

      <!-- Start Dropdown-add-to-list -->
      <!-- User logged in -->
      <% if current_user %>
        <button
                class="btn btn-flat dropdown-toggle"
                type="button"
                id="drop-down"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
                Save restaurant to your list
        </button>
        <div class="dropdown-menu" aria-labelledby="drop-down">
              <% user_lists = current_user.lists %>
              <%- if user_lists.empty? %>
                  <%= link_to "Create new list", new_user_list_path(current_user), class:"dropdown-item" %>
              <% else %>
                  <% user_lists.each do |list| %>
                    <%- if list.restaurants.include?(@restaurant)%>
                      <%= link_to user_list_path(current_user, list, restaurant: @restaurant, query: @query), method: :patch, class:"dropdown-item" do %>
                        <%= list.name %>  <i class="far fa-check-circle"></i>
                      <% end %>
                    <% else %>
                      <%= link_to list.name, user_list_path(current_user, list, restaurant: @restaurant, query: @query), method: :patch, class:"dropdown-item" %>
                    <% end %>
                  <% end %>
              <% end %>
        </div>
      <!-- User not logged in -->
      <% else %>
        <button
              class="btn btn-flat dropdown-toggle"
              type="button"
              id="drop-down"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false">
              Register to continue!
        </button>
        <div class="dropdown-menu" aria-labelledby="drop-down">
          <button
                type="button"
                class="dropdown-item"
                data-toggle="modal"
                data-target="#exampleModalB">
                Log in
          </button>
          <button
                type="button"
                class="dropdown-item"
                data-toggle="modal"
                data-target="#exampleModalA">
                Sign up
          </button>
        </div>
      <% end %>
      <!-- End Dropdown-add-to-list -->
    </div>
    <!-- End Switchboard (Section 2) -->
  </div>
  <!-- End Row 1 -->

  <!-- Start Row 2 -->
  <div class="row">
    <!-- Start Tags (Section 3) -->
    <div id="card-bg-long" class="col-11 shadow bg-white d-flex -center resto-section-3 mb-4 ml-2">
      <!-- Start Tags-Wrapper -->
      <div class="resto-tags">
        <!-- Start Tags-Display -->
        <div class="d-flex tags-display">
          <h5 class="mr-4">Tags: </h5>
          <ul class="tags">
          <% tags_array = @restaurant.tags.last(5) %>
          <% tags_array.each do |tag| %>
            <li class="resto-onetag">
              <a href="#" class="tag"><%= tag.name %></a>
              <a class="delete" href="#"><i class="fa fa-times"></i></a>
            </li>
          <% end %>
          </ul>
        </div>
        <!-- End Tags-Display -->
        <!-- Start Tags-Form -->
        <!-- div class="d-flex" -->
          <%#= simple_form_for [@restaurant, @tag], html: { class: "form-inline tags-form"} do |f| %>
            <!-- Add a new tag: -->
            <%#= f.input :name, label: false %>
            <%# f.association :user %>
            <%#= f.submit "Submit", class: "btn btn-flat" %>
          <%# end %>
        <!-- div -->
        <!-- End Tags-Form -->
      </div>
      <!-- End Tags-Wrapper -->
    </div>
    <!-- End Tags (Section 3) -->
  </div>
  <!-- End Row 2 -->

  <!-- Start Row 3 -->
  <div class="row">

  </div>
  <!-- End Row 3 -->

  <!-- Start Row 4 -->
  <h4> Reviews from other Foodies:</h4>
  <div class="row review-list">
    <!-- Start Reviews-Cards -->
    <% rest_array = @restaurant.reviews.last(3) %>
    <% rest_array.each do |review| %>
        <div class="review">
          <div class="d-flex justify-content-start">
            <p>Written by:<%= review.user.username %></p>
          </div>
          <div class="d-flex justify-content-start">
            <p>Rating given: <%= review.rating %></p>
          </div>
          <div class="list-review-content"><%= review.content %></div>
        </div>
    <% end %>
    <!-- End Reviews-Cards -->
  </div>
  <!-- End Row 4 -->

  <!-- Start Row 5 -->
  <div class="row">
    <!-- Start Review-Form -->
      <%= simple_form_for [@restaurant, @review], html: {class: "review-form col-11"} do |f| %>
          <div class="review-input">
            <%= f.input :content, placeholder: "Add your review:", label: false %>
          </div>
          <div class="review-input">
            <%= f.input :rating, collection: @drop_down, selected: "Rate your experience", label: false, input_html: {placeholder: "Rate your experience"} %>
          </div>
            <% f.association :user %>
          <div class="d-flex align-self-center">
            <%- if current_user %>
            <%= f.submit "Submit review", class: "btn btn-flat ml-2" %>
            <%#= link_to "My lists", user_lists_path(current_user), class: "btn btn-success"%>
            <% else %>
            <%= link_to "Back to search", results_path(query: params[:query]), class: "btn btn-flat-reverse ml-2" %>
            <p class="alert-main">Please log in or sign up to submit a review.</p>
            <% end %>
          </div>

      <% end %>
    </div>
    <!-- End Review-Form -->
  </div>
  <!-- End Row 5 -->

</div>
<!-- End Main Body -->